web:
    image: nginx:1.23-alpine
    restart: always
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./html:/usr/share/nginx/html:ro
    ports:
        - 8080:80
        - 8001:80
    environment:
        - NGINX_HOST= # HOST_NAME
        - NGINX_PORT=80
